project:
  type: website

website:
  title: "Trung Dam"
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: projector
        text: Projects
        menu:
          - text: Data Science
            href: data.qmd
          - text: Computer Science
            href: cs.qmd
      - icon: graph-up-arrow
        text: Tidy Tuesdays
        href: tidy_tuesday.qmd
      # - icon: search-heart
      #   text: Research
      #   menu:
      #     - text: Blocks4All
      #       href: blocks4all.qmd
    right: 
      - icon: github
        href: https://github.com/trungdam512
      - icon: linkedin
        href: https://www.linkedin.com/in/trung-dam-86962a235/ 

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual